/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Average: typeof import('./src/components/Average.vue')['default']
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    CompositInterest: typeof import('./src/components/CompositInterest.vue')['default']
    DatePage: typeof import('./src/pages/DatePage.vue')['default']
    DatesDifference: typeof import('./src/components/DatesDifference.vue')['default']
    DocumentReader: typeof import('./src/components/DocumentReader.vue')['default']
    ExapandableText: typeof import('./src/components/ExapandableText.vue')['default']
    Finance: typeof import('./src/components/Finance.vue')['default']
    FiscalCode: typeof import('./src/components/FiscalCode.vue')['default']
    FiscalCodePage: typeof import('./src/pages/FiscalCodePage.vue')['default']
    Geometry: typeof import('./src/components/Geometry.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    InversePercentage: typeof import('./src/components/InversePercentage.vue')['default']
    MyInput: typeof import('./src/components/MyInput.vue')['default']
    Percentage: typeof import('./src/components/Percentage.vue')['default']
    PercentagePage: typeof import('./src/pages/PercentagePage.vue')['default']
    ReversePercentage: typeof import('./src/components/ReversePercentage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnitMeasures: typeof import('./src/components/UnitMeasures.vue')['default']
    WidgetHeart: typeof import('./src/components/WidgetHeart.vue')['default']
  }
}
