/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Average: typeof import('./src/components/Average.vue')['default']
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    CompositInterest: typeof import('./src/components/CompositInterest.vue')['default']
    DatesDifference: typeof import('./src/components/DatesDifference.vue')['default']
    DocumentReader: typeof import('./src/components/DocumentReader.vue')['default']
    ExapandableText: typeof import('./src/components/ExapandableText.vue')['default']
    Finance: typeof import('./src/components/Finance.vue')['default']
    FiscalCode: typeof import('./src/components/FiscalCode.vue')['default']
    Geometry: typeof import('./src/components/Geometry.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    Percentages: typeof import('./src/components/Percentages.vue')['default']
    Proportion: typeof import('./src/components/Proportion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
    UnitMeasures: typeof import('./src/components/UnitMeasures.vue')['default']
    WidgetHeart: typeof import('./src/components/WidgetHeart.vue')['default']
  }
}
